PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS lots(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,type TEXT NOT NULL CHECK(type IN ('postura','corte')),breed TEXT,arrival_date TEXT NOT NULL,birth_date TEXT,initial_qty INTEGER NOT NULL DEFAULT 0,current_qty INTEGER NOT NULL DEFAULT 0,supplier TEXT,purchase_value REAL NOT NULL DEFAULT 0,shed TEXT,notes TEXT,photo_url TEXT,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS egg_production(id INTEGER PRIMARY KEY AUTOINCREMENT,lot_id INTEGER NOT NULL,date TEXT NOT NULL,good_eggs INTEGER DEFAULT 0,broken_eggs INTEGER DEFAULT 0,dirty_eggs INTEGER DEFAULT 0,small_eggs INTEGER DEFAULT 0,feed_kg REAL DEFAULT 0,notes TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(lot_id) REFERENCES lots(id));
CREATE TABLE IF NOT EXISTS broiler_weights(id INTEGER PRIMARY KEY AUTOINCREMENT,lot_id INTEGER NOT NULL,date TEXT NOT NULL,average_weight_kg REAL NOT NULL,quantity_weighed INTEGER DEFAULT 0,notes TEXT,FOREIGN KEY(lot_id) REFERENCES lots(id));
CREATE TABLE IF NOT EXISTS mortality(id INTEGER PRIMARY KEY AUTOINCREMENT,lot_id INTEGER,date TEXT NOT NULL,quantity INTEGER NOT NULL DEFAULT 0,possible_cause TEXT,notes TEXT,FOREIGN KEY(lot_id) REFERENCES lots(id));
CREATE TABLE IF NOT EXISTS feed_stock(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,type TEXT,quantity_kg REAL DEFAULT 0,min_stock_kg REAL DEFAULT 0,price_per_kg REAL DEFAULT 0,supplier TEXT,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS feed_consumption(id INTEGER PRIMARY KEY AUTOINCREMENT,lot_id INTEGER,date TEXT NOT NULL,quantity_kg REAL NOT NULL,feed_stock_id INTEGER,FOREIGN KEY(lot_id) REFERENCES lots(id),FOREIGN KEY(feed_stock_id) REFERENCES feed_stock(id));
CREATE TABLE IF NOT EXISTS health_events(id INTEGER PRIMARY KEY AUTOINCREMENT,lot_id INTEGER,type TEXT NOT NULL,title TEXT NOT NULL,event_date TEXT,due_date TEXT,status TEXT DEFAULT 'pendente',product TEXT,withdrawal_days INTEGER DEFAULT 0,responsible TEXT,notes TEXT,photo_url TEXT,FOREIGN KEY(lot_id) REFERENCES lots(id));
CREATE TABLE IF NOT EXISTS customers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,phone TEXT,address TEXT,notes TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sales(id INTEGER PRIMARY KEY AUTOINCREMENT,customer_id INTEGER,date TEXT NOT NULL,product_type TEXT NOT NULL,description TEXT,quantity REAL NOT NULL DEFAULT 1,unit_price REAL NOT NULL DEFAULT 0,total REAL NOT NULL DEFAULT 0,payment_method TEXT,payment_status TEXT DEFAULT 'pago',delivery_status TEXT,lot_id INTEGER,FOREIGN KEY(customer_id) REFERENCES customers(id),FOREIGN KEY(lot_id) REFERENCES lots(id));
CREATE TABLE IF NOT EXISTS expenses(id INTEGER PRIMARY KEY AUTOINCREMENT,date TEXT NOT NULL,category TEXT NOT NULL,description TEXT,amount REAL NOT NULL,lot_id INTEGER,supplier TEXT,FOREIGN KEY(lot_id) REFERENCES lots(id));
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,username TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'funcionario',active INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_egg_date ON egg_production(date);CREATE INDEX IF NOT EXISTS idx_feed_date ON feed_consumption(date);CREATE INDEX IF NOT EXISTS idx_sales_date ON sales(date);CREATE INDEX IF NOT EXISTS idx_expenses_date ON expenses(date);CREATE INDEX IF NOT EXISTS idx_health_due ON health_events(due_date);
-- Dados demonstrativos opcionais. Remova se desejar iniciar zerado.
INSERT OR IGNORE INTO lots(id,name,type,breed,arrival_date,initial_qty,current_qty,supplier,purchase_value,shed,notes) VALUES
(1,'P-01','postura','Lohmann Brown',date('now','-140 day'),1000,982,'Fornecedor Modelo',14500,'Galpão 1','Lote demonstrativo'),
(2,'C-01','corte','Cobb 500',date('now','-38 day'),600,575,'Fornecedor Modelo',4800,'Galpão 2','Lote demonstrativo');
INSERT OR IGNORE INTO feed_stock(id,name,type,quantity_kg,min_stock_kg,price_per_kg,supplier) VALUES(1,'Ração Postura Premium','postura',82,100,3.25,'Nutriaves'),(2,'Ração Terminação','terminacao',350,120,3.10,'Nutriaves');
