import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Bird, Egg, Wheat, Activity, WalletCards, AlertTriangle, LayoutDashboard, Boxes, HeartPulse, ShoppingCart, ReceiptText, Users, Settings, Menu, X, Moon, Sun, Plus, TrendingUp, Drumstick, CalendarDays, PackageOpen, BarChart3} from 'lucide-react';
import './styles.css';

type Dashboard={totalBirds:number;eggsToday:number;layRate:number;nearSlaughter:number;feedToday:number;mortalityToday:number;salesMonth:number;expensesMonth:number;estimatedProfit:number;alerts:Array<{level:string,title:string,detail:string}>};
type Lot={id:number;name:string;type:string;breed:string;arrival_date:string;initial_qty:number;current_qty:number;shed:string;purchase_value:number;notes?:string};
const money=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n||0);
const pct=(n:number)=>`${(n||0).toFixed(1)}%`;

const NAV=[
 ['dashboard','Visão geral',LayoutDashboard],['lots','Lotes',Boxes],['layers','Poedeiras',Egg],['broilers','Frangos de corte',Drumstick],['feed','Ração e estoque',Wheat],['health','Saúde e manejo',HeartPulse],['reproduction','Reprodução',Bird],['sales','Vendas e clientes',ShoppingCart],['finance','Financeiro',WalletCards],['reports','Relatórios',BarChart3],['users','Usuários',Users],['settings','Configurações',Settings]
] as const;

function App(){
 const [page,setPage]=useState('dashboard'); const [open,setOpen]=useState(false); const [dark,setDark]=useState(false);
 const [dash,setDash]=useState<Dashboard|null>(null); const [lots,setLots]=useState<Lot[]>([]); const [error,setError]=useState('');
 const [modal,setModal]=useState(false);
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light'},[dark]);
 async function load(){try{const [a,b]=await Promise.all([fetch('/api/dashboard'),fetch('/api/lots')]); if(!a.ok||!b.ok) throw new Error('API indisponível'); setDash(await a.json()); setLots(await b.json()); setError('')}catch(e:any){setError('Não foi possível carregar o banco. Se você ainda não configurou o D1, veja o README do projeto.')}}
 useEffect(()=>{load(); if('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(()=>{})},[]);
 const current=NAV.find(n=>n[0]===page)?.[1]||'Painel';
 return <div className="app">
   <aside className={`sidebar ${open?'open':''}`}><div className="brand"><div className="brandmark"><Bird size={24}/></div><div><b>Avicultura Pro</b><span>Gestão inteligente</span></div><button className="icon mobile" onClick={()=>setOpen(false)}><X/></button></div>
   <nav>{NAV.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setOpen(false)}}><Icon size={19}/><span>{label}</span></button>)}</nav>
   <div className="farm"><span>Propriedade</span><strong>Granja Modelo</strong><small>Plano profissional</small></div></aside>
   <main><header><div className="headleft"><button className="icon mobile" onClick={()=>setOpen(true)}><Menu/></button><div><small>Painel de gestão</small><h1>{current}</h1></div></div><div className="headright"><button className="icon" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button><div className="avatar">GM</div></div></header>
   <section className="content">{error&&<div className="notice"><AlertTriangle size={18}/><span>{error}</span></div>}{page==='dashboard'?<DashboardView d={dash}/>:page==='lots'?<Lots lots={lots} onNew={()=>setModal(true)}/>:page==='layers'?<SimpleModule kind="layers" lots={lots} onChanged={load}/>:page==='broilers'?<SimpleModule kind="broilers" lots={lots} onChanged={load}/>:page==='feed'?<SimpleModule kind="feed" lots={lots} onChanged={load}/>:page==='health'?<SimpleModule kind="health" lots={lots} onChanged={load}/>:page==='sales'?<SimpleModule kind="sales" lots={lots} onChanged={load}/>:page==='finance'?<SimpleModule kind="finance" lots={lots} onChanged={load}/>:page==='reports'?<Reports/>:<ModulePlaceholder page={page}/>}</section></main>
   {modal&&<LotModal onClose={()=>setModal(false)} onSaved={()=>{setModal(false);load()}}/>}
 </div>
}

function DashboardView({d}:{d:Dashboard|null}){const cards=[['Total de aves',d?.totalBirds??0,Bird,'aves'],['Ovos produzidos hoje',d?.eggsToday??0,Egg,'unidades'],['Taxa de postura',pct(d?.layRate??0),TrendingUp,'produção'],['Próximos do abate',d?.nearSlaughter??0,Drumstick,'aves'],['Ração consumida hoje',`${d?.feedToday??0} kg`,Wheat,'consumo'],['Mortalidade hoje',d?.mortalityToday??0,Activity,'registros']];return <>
 <div className="hero"><div><span className="eyebrow">Resumo operacional</span><h2>Bom dia 👋</h2><p>Acompanhe produção, estoque, saúde e resultado financeiro da propriedade em um só lugar.</p></div><div className="datechip"><CalendarDays size={18}/>Dados de hoje</div></div>
 <div className="metricgrid">{cards.map(([t,v,I,s]:any)=><div className="metric" key={t}><div className="metricicon"><I/></div><div><span>{t}</span><strong>{v}</strong><small>{s}</small></div></div>)}</div>
 <div className="grid2"><div className="panel"><div className="panelhead"><div><span className="eyebrow">Financeiro</span><h3>Resultado do mês</h3></div><ReceiptText/></div><div className="finance"><div><span>Vendas</span><b>{money(d?.salesMonth||0)}</b></div><div><span>Despesas</span><b>{money(d?.expensesMonth||0)}</b></div><div className="profit"><span>Lucro estimado</span><b>{money(d?.estimatedProfit||0)}</b></div></div></div>
 <div className="panel"><div className="panelhead"><div><span className="eyebrow">Atenção</span><h3>Alertas e próximos cuidados</h3></div><AlertTriangle/></div><div className="alerts">{(d?.alerts?.length?d.alerts:[{level:'info',title:'Tudo em dia',detail:'Nenhum alerta pendente no momento.'}]).map((a,i)=><div className={`alert ${a.level}`} key={i}><span className="dot"></span><div><b>{a.title}</b><small>{a.detail}</small></div></div>)}</div></div></div>
 </>}

function Lots({lots,onNew}:{lots:Lot[],onNew:()=>void}){return <><div className="toolbar"><div><span className="eyebrow">Plantel</span><h2>Cadastro de lotes</h2><p>Controle idade, alojamento, quantidade e custo de cada grupo de aves.</p></div><button className="primary" onClick={onNew}><Plus size={18}/>Novo lote</button></div><div className="tablepanel"><div className="tablewrap"><table><thead><tr><th>Lote</th><th>Tipo</th><th>Linhagem</th><th>Chegada</th><th>Quantidade</th><th>Galpão</th><th>Compra</th></tr></thead><tbody>{lots.length?lots.map(l=><tr key={l.id}><td><b>{l.name}</b></td><td><span className={`tag ${l.type}`}>{l.type==='postura'?'Postura':'Corte'}</span></td><td>{l.breed||'—'}</td><td>{l.arrival_date?new Date(l.arrival_date+'T12:00:00').toLocaleDateString('pt-BR'):'—'}</td><td>{l.current_qty} / {l.initial_qty}</td><td>{l.shed||'—'}</td><td>{money(l.purchase_value)}</td></tr>):<tr><td colSpan={7} className="empty">Nenhum lote cadastrado ainda.</td></tr>}</tbody></table></div></div></>}


function SimpleModule({kind,lots,onChanged}:{kind:string,lots:Lot[],onChanged:()=>void}){
 const configs:any={
  layers:{title:'Produção de ovos',desc:'Registre a produção diária por lote e acompanhe a qualidade dos ovos.',endpoint:'/api/egg-production',fields:[['date','Data','date'],['lot_id','Lote','lot'],['good_eggs','Ovos bons','number'],['broken_eggs','Quebrados','number'],['dirty_eggs','Sujos','number'],['small_eggs','Pequenos','number'],['feed_kg','Ração consumida (kg)','number']]},
  broilers:{title:'Pesagem de frangos',desc:'Acompanhe peso médio semanal e evolução dos lotes de corte.',endpoint:'/api/broiler-weights',fields:[['date','Data','date'],['lot_id','Lote de corte','lot-corte'],['average_weight_kg','Peso médio (kg)','number'],['quantity_weighed','Aves pesadas','number'],['notes','Observações','text']]},
  feed:{title:'Ração e estoque',desc:'Registre estoque, consumo e níveis mínimos de cada tipo de ração.',endpoint:'/api/feed-stock',fields:[['name','Nome da ração','text'],['type','Tipo','feedtype'],['quantity_kg','Quantidade (kg)','number'],['min_stock_kg','Estoque mínimo (kg)','number'],['price_per_kg','Preço por kg','number'],['supplier','Fornecedor','text']]},
  health:{title:'Saúde e manejo',desc:'Registre vacinas, manejo e ocorrências. O sistema não realiza diagnóstico veterinário.',endpoint:'/api/health-events',fields:[['lot_id','Lote','lot'],['type','Tipo','healthtype'],['title','Evento','text'],['event_date','Data realizada','date'],['due_date','Próxima data','date'],['responsible','Responsável','text'],['notes','Observações','text']]},
  sales:{title:'Vendas',desc:'Registre vendas de ovos, frangos, aves de descarte e outros produtos.',endpoint:'/api/sales',fields:[['date','Data','date'],['product_type','Produto','product'],['description','Descrição','text'],['quantity','Quantidade','number'],['unit_price','Preço unitário','number'],['payment_method','Pagamento','payment']]},
  finance:{title:'Despesas',desc:'Registre custos e despesas para compor o resultado financeiro mensal.',endpoint:'/api/expenses',fields:[['date','Data','date'],['category','Categoria','expensecat'],['description','Descrição','text'],['amount','Valor','number'],['supplier','Fornecedor','text']]}
 };
 const c=configs[kind]; const [rows,setRows]=useState<any[]>([]); const [busy,setBusy]=useState(false);
 async function refresh(){try{const r=await fetch(c.endpoint);if(r.ok)setRows(await r.json())}catch{}}
 useEffect(()=>{refresh()},[kind]);
 async function submit(e:any){e.preventDefault();setBusy(true);const body=Object.fromEntries(new FormData(e.currentTarget).entries());const r=await fetch(c.endpoint,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});setBusy(false);if(r.ok){e.currentTarget.reset();refresh();onChanged()}else alert('Não foi possível salvar o registro.')}
 return <><div className="toolbar"><div><span className="eyebrow">Operação</span><h2>{c.title}</h2><p>{c.desc}</p></div></div><div className="gridform"><div className="panel"><h3>Novo registro</h3><form onSubmit={submit}><div className="formgrid">{c.fields.map((f:any)=><Field key={f[0]} f={f} lots={lots}/>)}</div><div className="modalactions"><button className="primary" disabled={busy}>{busy?'Salvando...':'Salvar registro'}</button></div></form></div><div className="panel"><div className="panelhead"><div><span className="eyebrow">Histórico</span><h3>Registros recentes</h3></div></div><div className="recentlist">{rows.length?rows.slice(0,8).map((r:any,i:number)=><div className="recent" key={r.id||i}><b>{r.name||r.title||r.description||r.product_type||`Registro #${r.id}`}</b><span>{r.date||r.event_date||r.due_date||r.updated_at||''}</span><small>{formatSummary(kind,r)}</small></div>):<div className="emptycard">Nenhum registro ainda.</div>}</div></div></div></>
}
function Field({f,lots}:{f:any,lots:Lot[]}){const [name,label,type]=f;if(type==='lot'||type==='lot-corte'){const xs=type==='lot-corte'?lots.filter(l=>l.type==='corte'):lots;return <label>{label}<select name={name} required><option value="">Selecione</option>{xs.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label>}if(type==='feedtype')return <label>{label}<select name={name}><option>pré-inicial</option><option>inicial</option><option>crescimento</option><option>pré-postura</option><option>postura</option><option>terminação</option></select></label>;if(type==='healthtype')return <label>{label}<select name={name}><option value="vacina">Vacina</option><option value="medicamento">Medicamento</option><option value="manejo">Manejo</option><option value="limpeza">Limpeza/desinfecção</option><option value="sintoma">Sinal observado</option></select></label>;if(type==='product')return <label>{label}<select name={name}><option value="ovos">Ovos</option><option value="frangos">Frangos</option><option value="descarte">Aves de descarte</option><option value="esterco">Esterco</option><option value="outros">Outros</option></select></label>;if(type==='payment')return <label>{label}<select name={name}><option>Pix</option><option>Dinheiro</option><option>Cartão</option><option>A prazo</option></select></label>;if(type==='expensecat')return <label>{label}<select name={name}><option>Ração</option><option>Aves</option><option>Vacinas e medicamentos</option><option>Energia</option><option>Água</option><option>Embalagens</option><option>Funcionários</option><option>Transporte</option><option>Manutenção</option><option>Outros</option></select></label>;return <label>{label}<input name={name} type={type==='number'?'number':type} step={type==='number'?'0.01':undefined} required={!['notes','description','supplier','event_date'].includes(name)}/></label>}
function formatSummary(kind:string,r:any){if(kind==='layers')return `${(r.good_eggs||0)+(r.broken_eggs||0)+(r.dirty_eggs||0)+(r.small_eggs||0)} ovos • ${r.feed_kg||0} kg ração`;if(kind==='broilers')return `${r.average_weight_kg||0} kg de peso médio`;if(kind==='feed')return `${r.quantity_kg||0} kg disponíveis • mínimo ${r.min_stock_kg||0} kg`;if(kind==='sales')return `${r.quantity||0} × ${money(r.unit_price||0)} = ${money(r.total||0)}`;if(kind==='finance')return `${r.category||''} • ${money(r.amount||0)}`;return r.type||''}
function Reports(){function csv(){window.location.href='/api/reports/monthly.csv'} function print(){window.print()}return <div className="placeholder"><div className="bigicon"><BarChart3 size={34}/></div><span className="eyebrow">Relatórios</span><h2>Fechamento mensal</h2><p>Exporte os dados consolidados em planilha CSV ou use a impressão do navegador para gerar PDF e compartilhar pelo WhatsApp.</p><div className="reportactions"><button className="primary" onClick={csv}>Exportar planilha CSV</button><button className="secondary" onClick={print}>Gerar PDF / Imprimir</button></div></div>}

function ModulePlaceholder({page}:{page:string}){const item=NAV.find(n=>n[0]===page)!; const Icon=item[2]; return <div className="placeholder"><div className="bigicon"><Icon size={34}/></div><span className="eyebrow">Módulo preparado</span><h2>{item[1]}</h2><p>A estrutura de navegação e banco foi preparada para este módulo. Ele pode receber os formulários, indicadores e relatórios específicos sem alterar a arquitetura principal.</p><div className="coming"><PackageOpen size={18}/>Base pronta para evolução</div></div>}

function LotModal({onClose,onSaved}:{onClose:()=>void,onSaved:()=>void}){const [busy,setBusy]=useState(false); async function submit(e:any){e.preventDefault();setBusy(true);const fd=new FormData(e.currentTarget);const body=Object.fromEntries(fd.entries());const r=await fetch('/api/lots',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});setBusy(false); if(r.ok) onSaved(); else alert('Não foi possível salvar. Verifique a configuração do D1.')}return <div className="modalback"><div className="modal"><div className="modalhead"><div><span className="eyebrow">Cadastro</span><h3>Novo lote</h3></div><button className="icon" onClick={onClose}><X/></button></div><form onSubmit={submit}><div className="formgrid"><label>Nome/número<input name="name" required placeholder="Ex.: P-2026-01"/></label><label>Tipo<select name="type"><option value="postura">Postura</option><option value="corte">Corte</option></select></label><label>Raça/linhagem<input name="breed" placeholder="Ex.: Lohmann Brown"/></label><label>Data de chegada<input type="date" name="arrival_date" required/></label><label>Quantidade comprada<input type="number" name="initial_qty" min="1" required/></label><label>Quantidade atual<input type="number" name="current_qty" min="0" required/></label><label>Fornecedor<input name="supplier"/></label><label>Valor da compra<input type="number" step="0.01" name="purchase_value"/></label><label>Galpão<input name="shed"/></label><label className="wide">Observações<textarea name="notes" rows={3}/></label></div><div className="modalactions"><button type="button" className="secondary" onClick={onClose}>Cancelar</button><button className="primary" disabled={busy}>{busy?'Salvando...':'Salvar lote'}</button></div></form></div></div>}

createRoot(document.getElementById('root')!).render(<App/>);
