interface Env { DB: D1Database; ASSETS: Fetcher }
const json=(data:any,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8'}})
export default {async fetch(request:Request,env:Env):Promise<Response>{const u=new URL(request.url);try{
 if(u.pathname==='/api/health') return json({ok:true});
 if(u.pathname==='/api/dashboard'&&request.method==='GET'){
  const total=(await env.DB.prepare('SELECT COALESCE(SUM(current_qty),0) total FROM lots WHERE active=1').first<any>())?.total||0;
  const prod=await env.DB.prepare("SELECT COALESCE(SUM(good_eggs+broken_eggs+dirty_eggs+small_eggs),0) eggs FROM egg_production WHERE date=date('now')").first<any>();
  const deaths=(await env.DB.prepare("SELECT COALESCE(SUM(quantity),0) qty FROM mortality WHERE date=date('now')").first<any>())?.qty||0;
  const feed=(await env.DB.prepare("SELECT COALESCE(SUM(quantity_kg),0) kg FROM feed_consumption WHERE date=date('now')").first<any>())?.kg||0;
  const sales=(await env.DB.prepare("SELECT COALESCE(SUM(total),0) v FROM sales WHERE strftime('%Y-%m',date)=strftime('%Y-%m','now')").first<any>())?.v||0;
  const expenses=(await env.DB.prepare("SELECT COALESCE(SUM(amount),0) v FROM expenses WHERE strftime('%Y-%m',date)=strftime('%Y-%m','now')").first<any>())?.v||0;
  const layerAlive=(await env.DB.prepare("SELECT COALESCE(SUM(current_qty),0) qty FROM lots WHERE active=1 AND type='postura'").first<any>())?.qty||0;
  const eggs=prod?.eggs||0; const layRate=layerAlive?eggs/layerAlive*100:0;
  const near=(await env.DB.prepare("SELECT COALESCE(SUM(current_qty),0) qty FROM lots WHERE active=1 AND type='corte' AND julianday('now')-julianday(arrival_date)>=35").first<any>())?.qty||0;
  const alerts=[] as any[];
  const low=await env.DB.prepare('SELECT name, quantity_kg, min_stock_kg FROM feed_stock WHERE quantity_kg<=min_stock_kg ORDER BY quantity_kg ASC LIMIT 3').all<any>();
  low.results.forEach((r:any)=>alerts.push({level:'warning',title:`Estoque baixo: ${r.name}`,detail:`Restam ${Number(r.quantity_kg).toFixed(1)} kg.`}));
  const vacc=await env.DB.prepare("SELECT title,due_date FROM health_events WHERE type='vacina' AND status='pendente' AND due_date BETWEEN date('now') AND date('now','+7 day') ORDER BY due_date LIMIT 3").all<any>();
  vacc.results.forEach((r:any)=>alerts.push({level:'danger',title:r.title,detail:`Programado para ${r.due_date}.`}));
  return json({totalBirds:total,eggsToday:eggs,layRate,nearSlaughter:near,feedToday:feed,mortalityToday:deaths,salesMonth:sales,expensesMonth:expenses,estimatedProfit:sales-expenses,alerts});
 }
 if(u.pathname==='/api/lots'&&request.method==='GET'){const r=await env.DB.prepare('SELECT * FROM lots WHERE active=1 ORDER BY id DESC').all();return json(r.results)}
 if(u.pathname==='/api/lots'&&request.method==='POST'){const b:any=await request.json();if(!b.name||!b.type||!b.arrival_date)return json({error:'Campos obrigatórios ausentes'},400);const q=Number(b.current_qty||b.initial_qty||0),initial=Number(b.initial_qty||0);const r=await env.DB.prepare('INSERT INTO lots(name,type,breed,arrival_date,initial_qty,current_qty,supplier,purchase_value,shed,notes,active) VALUES(?,?,?,?,?,?,?,?,?,?,1)').bind(b.name,b.type,b.breed||'',b.arrival_date,initial,q,b.supplier||'',Number(b.purchase_value||0),b.shed||'',b.notes||'').run();return json({ok:true,id:r.meta.last_row_id},201)}
 if(u.pathname==='/api/egg-production'&&request.method==='GET'){const r=await env.DB.prepare('SELECT e.*,l.name lot_name FROM egg_production e LEFT JOIN lots l ON l.id=e.lot_id ORDER BY e.date DESC,e.id DESC LIMIT 100').all();return json(r.results)}
 if(u.pathname==='/api/egg-production'&&request.method==='POST'){const b:any=await request.json();const r=await env.DB.prepare('INSERT INTO egg_production(lot_id,date,good_eggs,broken_eggs,dirty_eggs,small_eggs,feed_kg,notes) VALUES(?,?,?,?,?,?,?,?)').bind(Number(b.lot_id),b.date,Number(b.good_eggs||0),Number(b.broken_eggs||0),Number(b.dirty_eggs||0),Number(b.small_eggs||0),Number(b.feed_kg||0),b.notes||'').run();return json({ok:true,id:r.meta.last_row_id},201)}
 if(u.pathname==='/api/broiler-weights'&&request.method==='GET'){const r=await env.DB.prepare('SELECT w.*,l.name lot_name FROM broiler_weights w LEFT JOIN lots l ON l.id=w.lot_id ORDER BY w.date DESC,w.id DESC LIMIT 100').all();return json(r.results)}
 if(u.pathname==='/api/broiler-weights'&&request.method==='POST'){const b:any=await request.json();const r=await env.DB.prepare('INSERT INTO broiler_weights(lot_id,date,average_weight_kg,quantity_weighed,notes) VALUES(?,?,?,?,?)').bind(Number(b.lot_id),b.date,Number(b.average_weight_kg||0),Number(b.quantity_weighed||0),b.notes||'').run();return json({ok:true,id:r.meta.last_row_id},201)}
 if(u.pathname==='/api/feed-stock'&&request.method==='GET'){const r=await env.DB.prepare('SELECT * FROM feed_stock ORDER BY updated_at DESC,id DESC LIMIT 100').all();return json(r.results)}
 if(u.pathname==='/api/feed-stock'&&request.method==='POST'){const b:any=await request.json();const r=await env.DB.prepare('INSERT INTO feed_stock(name,type,quantity_kg,min_stock_kg,price_per_kg,supplier,updated_at) VALUES(?,?,?,?,?,?,CURRENT_TIMESTAMP)').bind(b.name,b.type||'',Number(b.quantity_kg||0),Number(b.min_stock_kg||0),Number(b.price_per_kg||0),b.supplier||'').run();return json({ok:true,id:r.meta.last_row_id},201)}
 if(u.pathname==='/api/health-events'&&request.method==='GET'){const r=await env.DB.prepare('SELECT h.*,l.name lot_name FROM health_events h LEFT JOIN lots l ON l.id=h.lot_id ORDER BY COALESCE(h.due_date,h.event_date) DESC,h.id DESC LIMIT 100').all();return json(r.results)}
 if(u.pathname==='/api/health-events'&&request.method==='POST'){const b:any=await request.json();const status=b.due_date?'pendente':'concluido';const r=await env.DB.prepare('INSERT INTO health_events(lot_id,type,title,event_date,due_date,status,responsible,notes) VALUES(?,?,?,?,?,?,?,?)').bind(Number(b.lot_id)||null,b.type,b.title,b.event_date||null,b.due_date||null,status,b.responsible||'',b.notes||'').run();return json({ok:true,id:r.meta.last_row_id},201)}
 if(u.pathname==='/api/sales'&&request.method==='GET'){const r=await env.DB.prepare('SELECT * FROM sales ORDER BY date DESC,id DESC LIMIT 100').all();return json(r.results)}
 if(u.pathname==='/api/sales'&&request.method==='POST'){const b:any=await request.json();const total=Number(b.quantity||0)*Number(b.unit_price||0);const r=await env.DB.prepare('INSERT INTO sales(date,product_type,description,quantity,unit_price,total,payment_method,payment_status) VALUES(?,?,?,?,?,?,?,?)').bind(b.date,b.product_type,b.description||'',Number(b.quantity||0),Number(b.unit_price||0),total,b.payment_method||'',b.payment_method==='A prazo'?'pendente':'pago').run();return json({ok:true,id:r.meta.last_row_id},201)}
 if(u.pathname==='/api/expenses'&&request.method==='GET'){const r=await env.DB.prepare('SELECT * FROM expenses ORDER BY date DESC,id DESC LIMIT 100').all();return json(r.results)}
 if(u.pathname==='/api/expenses'&&request.method==='POST'){const b:any=await request.json();const r=await env.DB.prepare('INSERT INTO expenses(date,category,description,amount,supplier) VALUES(?,?,?,?,?)').bind(b.date,b.category,b.description||'',Number(b.amount||0),b.supplier||'').run();return json({ok:true,id:r.meta.last_row_id},201)}
 if(u.pathname==='/api/reports/monthly.csv'&&request.method==='GET'){
   const ym=u.searchParams.get('month')||new Date().toISOString().slice(0,7);const sales=await env.DB.prepare("SELECT date,product_type,description,quantity,unit_price,total,payment_method FROM sales WHERE substr(date,1,7)=? ORDER BY date").bind(ym).all<any>();const ex=await env.DB.prepare("SELECT date,category,description,amount,supplier FROM expenses WHERE substr(date,1,7)=? ORDER BY date").bind(ym).all<any>();
   const esc=(v:any)=>`"${String(v??'').replaceAll('"','""')}"`;let csv='RELATORIO MENSAL;'+ym+'\n\nVENDAS\nData;Produto;Descricao;Quantidade;Preco Unitario;Total;Pagamento\n';for(const r of sales.results)csv+=[r.date,r.product_type,r.description,r.quantity,r.unit_price,r.total,r.payment_method].map(esc).join(';')+'\n';csv+='\nDESPESAS\nData;Categoria;Descricao;Valor;Fornecedor\n';for(const r of ex.results)csv+=[r.date,r.category,r.description,r.amount,r.supplier].map(esc).join(';')+'\n';return new Response('\ufeff'+csv,{headers:{'content-type':'text/csv; charset=utf-8','content-disposition':`attachment; filename="avicultura-${ym}.csv"`}})
 }
 return env.ASSETS.fetch(request)
 }catch(e:any){return json({error:'Erro interno',detail:e?.message||String(e)},500)}}}
