export interface Env { DB:D1Database; ASSETS:Fetcher }
const enc=new TextEncoder();
const json=(data:any,status=200,headers:HeadersInit={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8',...headers}});
const b64=(u8:Uint8Array)=>btoa(String.fromCharCode(...u8));
const hex=(u8:Uint8Array)=>[...u8].map(b=>b.toString(16).padStart(2,'0')).join('');
async function sha(s:string){return hex(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(s))))}
async function hashPassword(p:string,salt?:string){const s=salt||b64(crypto.getRandomValues(new Uint8Array(16)));const key=await crypto.subtle.importKey('raw',enc.encode(p),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:enc.encode(s),iterations:120000,hash:'SHA-256'},key,256);return {hash:hex(new Uint8Array(bits)),salt:s}}
const cookie=(r:Request,n:string)=>{const m=(r.headers.get('cookie')||'').match(new RegExp('(?:^|; )'+n+'=([^;]*)'));return m?decodeURIComponent(m[1]):''};
async function currentUser(r:Request,env:Env){const token=cookie(r,'avic_session');if(!token)return null;const th=await sha(token);return await env.DB.prepare("SELECT u.id,u.name,u.username,u.role,u.active FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>datetime('now') AND u.active=1").bind(th).first<any>();}
async function body(r:Request){return await r.json() as any}
async function isAdmin(u:any){return u&&['proprietaria','gerente'].includes(u.role)}
function num(v:any){const n=Number(v);return Number.isFinite(n)?n:0}
async function dashboard(env:Env){
 const today=new Date().toISOString().slice(0,10), ym=today.slice(0,7);
 const lots=await env.DB.prepare('SELECT COALESCE(SUM(current_qty),0) total FROM lots WHERE active=1').first<any>();
 const eggs=await env.DB.prepare('SELECT COALESCE(SUM(good_eggs+broken_eggs+dirty_eggs+small_eggs),0) n,COALESCE(SUM(feed_kg),0) feed FROM egg_production WHERE date=?').bind(today).first<any>();
 const aliveLayers=await env.DB.prepare("SELECT COALESCE(SUM(current_qty),0) n FROM lots WHERE active=1 AND type='postura'").first<any>();
 const cut=await env.DB.prepare("SELECT COALESCE(SUM(current_qty),0) n FROM lots WHERE active=1 AND type='corte' AND julianday('now')-julianday(arrival_date)>=35").first<any>();
 const mort=await env.DB.prepare('SELECT COALESCE(SUM(quantity),0) n FROM mortality WHERE date=?').bind(today).first<any>();
 const feed=await env.DB.prepare('SELECT COALESCE(SUM(quantity_kg),0) n FROM feed_consumption WHERE date=?').bind(today).first<any>();
 const sales=await env.DB.prepare("SELECT COALESCE(SUM(total),0) n FROM sales WHERE substr(date,1,7)=?").bind(ym).first<any>();
 const exp=await env.DB.prepare("SELECT COALESCE(SUM(amount),0) n FROM expenses WHERE substr(date,1,7)=?").bind(ym).first<any>();
 const stock=await env.DB.prepare('SELECT name,quantity_kg,min_stock_kg FROM feed_stock WHERE quantity_kg<=min_stock_kg ORDER BY quantity_kg ASC LIMIT 4').all<any>();
 const health=await env.DB.prepare("SELECT title,due_date FROM health_events WHERE status='pendente' AND due_date IS NOT NULL AND due_date<=date('now','+7 day') ORDER BY due_date LIMIT 4").all<any>();
 const alerts=[...stock.results.map((x:any)=>({level:'danger',title:`Ração baixa: ${x.name}`,detail:`${x.quantity_kg} kg disponíveis (mínimo ${x.min_stock_kg} kg)`})),...health.results.map((x:any)=>({level:'warning',title:x.title,detail:`Programado para ${x.due_date}`}))];
 return {totalBirds:num(lots?.total),eggsToday:num(eggs?.n),layRate:num(aliveLayers?.n)?num(eggs?.n)/num(aliveLayers.n)*100:0,nearSlaughter:num(cut?.n),feedToday:num(feed?.n)+num(eggs?.feed),mortalityToday:num(mort?.n),salesMonth:num(sales?.n),expensesMonth:num(exp?.n),estimatedProfit:num(sales?.n)-num(exp?.n),alerts};
}
export default {async fetch(request:Request,env:Env){try{
 const u=new URL(request.url), p=u.pathname, m=request.method;
 if(p==='/api/auth/status'){const count=await env.DB.prepare('SELECT COUNT(*) n FROM users').first<any>();return json({setupRequired:num(count?.n)===0,user:await currentUser(request,env)})}
 if(p==='/api/auth/setup'&&m==='POST'){const c=await env.DB.prepare('SELECT COUNT(*) n FROM users').first<any>();if(num(c?.n)>0)return json({error:'Configuração inicial já realizada.'},409);const b=await body(request);if(!b.name||!b.username||String(b.password||'').length<6)return json({error:'Informe nome, usuário e senha com pelo menos 6 caracteres.'},400);const hp=await hashPassword(String(b.password));await env.DB.prepare("INSERT INTO users(name,username,password_hash,password_salt,role) VALUES(?,?,?,?, 'proprietaria')").bind(b.name,String(b.username).trim().toLowerCase(),hp.hash,hp.salt).run();return json({ok:true},201)}
 if(p==='/api/auth/login'&&m==='POST'){const b=await body(request);const usr=await env.DB.prepare('SELECT * FROM users WHERE username=? AND active=1').bind(String(b.username||'').trim().toLowerCase()).first<any>();if(!usr)return json({error:'Usuário ou senha inválidos.'},401);const hp=await hashPassword(String(b.password||''),usr.password_salt);if(hp.hash!==usr.password_hash)return json({error:'Usuário ou senha inválidos.'},401);const token=b64(crypto.getRandomValues(new Uint8Array(32))).replaceAll('=','');const th=await sha(token);await env.DB.prepare("INSERT INTO sessions(token_hash,user_id,expires_at) VALUES(?,?,datetime('now','+30 day'))").bind(th,usr.id).run();return json({ok:true,user:{id:usr.id,name:usr.name,username:usr.username,role:usr.role}},200,{'set-cookie':`avic_session=${encodeURIComponent(token)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=2592000`})}
 if(p==='/api/auth/logout'&&m==='POST'){const t=cookie(request,'avic_session');if(t)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha(t)).run();return json({ok:true},200,{'set-cookie':'avic_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0'})}
 if(!p.startsWith('/api/'))return env.ASSETS.fetch(request);
 const user=await currentUser(request,env);if(!user)return json({error:'Não autenticado'},401);
 if(p==='/api/dashboard')return json(await dashboard(env));
 if(p==='/api/settings'&&m==='GET'){const r=await env.DB.prepare('SELECT key,value FROM settings').all<any>();return json(Object.fromEntries(r.results.map((x:any)=>[x.key,x.value])))}
 if(p==='/api/settings'&&m==='POST'){if(!await isAdmin(user))return json({error:'Sem permissão'},403);const b=await body(request);for(const [k,v] of Object.entries(b))await env.DB.prepare("INSERT INTO settings(key,value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP").bind(k,String(v??'')).run();return json({ok:true})}
 if(p==='/api/lots'&&m==='GET'){const r=await env.DB.prepare("SELECT *,CAST(julianday('now')-julianday(COALESCE(birth_date,arrival_date)) AS INTEGER) age_days FROM lots WHERE active=1 ORDER BY id DESC").all();return json(r.results)}
 if(p==='/api/lots'&&m==='POST'){const b=await body(request);if(!b.name||!b.type||!b.arrival_date)return json({error:'Campos obrigatórios ausentes'},400);const r=await env.DB.prepare('INSERT INTO lots(name,type,breed,arrival_date,birth_date,initial_qty,current_qty,supplier,purchase_value,shed,notes,photo_url) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(b.name,b.type,b.breed||'',b.arrival_date,b.birth_date||null,num(b.initial_qty),num(b.current_qty||b.initial_qty),b.supplier||'',num(b.purchase_value),b.shed||'',b.notes||'',b.photo_url||'').run();return json({ok:true,id:r.meta.last_row_id},201)}
 if(p.match(/^\/api\/lots\/\d+$/)&&m==='DELETE'){if(!await isAdmin(user))return json({error:'Sem permissão'},403);const id=p.split('/').pop();await env.DB.prepare('UPDATE lots SET active=0 WHERE id=?').bind(id).run();return json({ok:true})}
 const maps:any={
  '/api/egg-production':{get:'SELECT e.*,l.name lot_name,l.current_qty live_birds FROM egg_production e LEFT JOIN lots l ON l.id=e.lot_id ORDER BY e.date DESC,e.id DESC LIMIT 300',ins:'INSERT INTO egg_production(lot_id,date,good_eggs,broken_eggs,dirty_eggs,small_eggs,feed_kg,notes) VALUES(?,?,?,?,?,?,?,?)',vals:(b:any)=>[num(b.lot_id),b.date,num(b.good_eggs),num(b.broken_eggs),num(b.dirty_eggs),num(b.small_eggs),num(b.feed_kg),b.notes||'']},
  '/api/broiler-weights':{get:'SELECT w.*,l.name lot_name FROM broiler_weights w LEFT JOIN lots l ON l.id=w.lot_id ORDER BY w.date DESC,w.id DESC LIMIT 300',ins:'INSERT INTO broiler_weights(lot_id,date,average_weight_kg,quantity_weighed,notes) VALUES(?,?,?,?,?)',vals:(b:any)=>[num(b.lot_id),b.date,num(b.average_weight_kg),num(b.quantity_weighed),b.notes||'']},
  '/api/mortality':{get:'SELECT m.*,l.name lot_name FROM mortality m LEFT JOIN lots l ON l.id=m.lot_id ORDER BY m.date DESC,m.id DESC LIMIT 300',ins:'INSERT INTO mortality(lot_id,date,quantity,possible_cause,notes) VALUES(?,?,?,?,?)',vals:(b:any)=>[num(b.lot_id)||null,b.date,num(b.quantity),b.possible_cause||'',b.notes||'']},
  '/api/health-events':{get:'SELECT h.*,l.name lot_name FROM health_events h LEFT JOIN lots l ON l.id=h.lot_id ORDER BY COALESCE(h.due_date,h.event_date) DESC,h.id DESC LIMIT 300',ins:'INSERT INTO health_events(lot_id,type,title,event_date,due_date,status,product,withdrawal_days,responsible,notes,photo_url) VALUES(?,?,?,?,?,?,?,?,?,?,?)',vals:(b:any)=>[num(b.lot_id)||null,b.type,b.title,b.event_date||null,b.due_date||null,b.status||'pendente',b.product||'',num(b.withdrawal_days),b.responsible||'',b.notes||'',b.photo_url||'']},
  '/api/reproduction':{get:'SELECT r.*,l.name lot_name FROM reproduction r LEFT JOIN lots l ON l.id=r.lot_id ORDER BY r.entry_date DESC,r.id DESC LIMIT 300',ins:'INSERT INTO reproduction(lot_id,incubator,entry_date,hatch_due_date,eggs_set,fertile_eggs,chicks_hatched,chicks_discarded,notes) VALUES(?,?,?,?,?,?,?,?,?)',vals:(b:any)=>[num(b.lot_id)||null,b.incubator||'',b.entry_date,b.hatch_due_date||null,num(b.eggs_set),num(b.fertile_eggs),num(b.chicks_hatched),num(b.chicks_discarded),b.notes||'']},
  '/api/customers':{get:'SELECT * FROM customers ORDER BY name',ins:'INSERT INTO customers(name,phone,address,notes) VALUES(?,?,?,?)',vals:(b:any)=>[b.name,b.phone||'',b.address||'',b.notes||'']},
  '/api/expenses':{get:'SELECT e.*,l.name lot_name FROM expenses e LEFT JOIN lots l ON l.id=e.lot_id ORDER BY e.date DESC,e.id DESC LIMIT 300',ins:'INSERT INTO expenses(date,category,description,amount,lot_id,supplier) VALUES(?,?,?,?,?,?)',vals:(b:any)=>[b.date,b.category,b.description||'',num(b.amount),num(b.lot_id)||null,b.supplier||'']}
 };
 if(maps[p]){if(m==='GET'){const r=await env.DB.prepare(maps[p].get).all();return json(r.results)}if(m==='POST'){const b=await body(request),v=maps[p].vals(b);const r=await env.DB.prepare(maps[p].ins).bind(...v).run();return json({ok:true,id:r.meta.last_row_id},201)}}
 if(p==='/api/feed-stock'&&m==='GET'){const r=await env.DB.prepare('SELECT *,CASE WHEN quantity_kg<=min_stock_kg THEN 1 ELSE 0 END low FROM feed_stock ORDER BY updated_at DESC,id DESC').all();return json(r.results)}
 if(p==='/api/feed-stock'&&m==='POST'){const b=await body(request);const r=await env.DB.prepare('INSERT INTO feed_stock(name,type,quantity_kg,min_stock_kg,price_per_kg,supplier,updated_at) VALUES(?,?,?,?,?,?,CURRENT_TIMESTAMP)').bind(b.name,b.type||'',num(b.quantity_kg),num(b.min_stock_kg),num(b.price_per_kg),b.supplier||'').run();return json({ok:true,id:r.meta.last_row_id},201)}
 if(p==='/api/feed-consumption'&&m==='GET'){const r=await env.DB.prepare('SELECT c.*,l.name lot_name,f.name feed_name FROM feed_consumption c LEFT JOIN lots l ON l.id=c.lot_id LEFT JOIN feed_stock f ON f.id=c.feed_stock_id ORDER BY c.date DESC,c.id DESC LIMIT 300').all();return json(r.results)}
 if(p==='/api/feed-consumption'&&m==='POST'){const b=await body(request),qty=num(b.quantity_kg),fid=num(b.feed_stock_id);await env.DB.batch([env.DB.prepare('INSERT INTO feed_consumption(lot_id,date,quantity_kg,feed_stock_id) VALUES(?,?,?,?)').bind(num(b.lot_id),b.date,qty,fid),env.DB.prepare('UPDATE feed_stock SET quantity_kg=MAX(0,quantity_kg-?),updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(qty,fid)]);return json({ok:true},201)}
 if(p==='/api/sales'&&m==='GET'){const r=await env.DB.prepare('SELECT s.*,c.name customer_name,l.name lot_name FROM sales s LEFT JOIN customers c ON c.id=s.customer_id LEFT JOIN lots l ON l.id=s.lot_id ORDER BY s.date DESC,s.id DESC LIMIT 300').all();return json(r.results)}
 if(p==='/api/sales'&&m==='POST'){const b=await body(request),total=num(b.quantity)*num(b.unit_price);const r=await env.DB.prepare('INSERT INTO sales(customer_id,date,product_type,description,quantity,unit_price,total,payment_method,payment_status,delivery_status,lot_id) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(num(b.customer_id)||null,b.date,b.product_type,b.description||'',num(b.quantity),num(b.unit_price),total,b.payment_method||'',b.payment_status||'pago',b.delivery_status||'pendente',num(b.lot_id)||null).run();return json({ok:true,id:r.meta.last_row_id},201)}
 if(p==='/api/users'&&m==='GET'){if(!await isAdmin(user))return json({error:'Sem permissão'},403);const r=await env.DB.prepare('SELECT id,name,username,role,active,created_at FROM users ORDER BY name').all();return json(r.results)}
 if(p==='/api/users'&&m==='POST'){if(!await isAdmin(user))return json({error:'Sem permissão'},403);const b=await body(request);if(!b.name||!b.username||String(b.password||'').length<6)return json({error:'Preencha nome, usuário e senha mínima de 6 caracteres.'},400);const hp=await hashPassword(String(b.password));const r=await env.DB.prepare('INSERT INTO users(name,username,password_hash,password_salt,role) VALUES(?,?,?,?,?)').bind(b.name,String(b.username).trim().toLowerCase(),hp.hash,hp.salt,b.role||'funcionario').run();return json({ok:true,id:r.meta.last_row_id},201)}
 if(p.match(/^\/api\/users\/\d+\/toggle$/)&&m==='POST'){if(!await isAdmin(user))return json({error:'Sem permissão'},403);const id=p.split('/')[3];if(num(id)===user.id)return json({error:'Você não pode desativar seu próprio acesso.'},400);await env.DB.prepare('UPDATE users SET active=CASE active WHEN 1 THEN 0 ELSE 1 END WHERE id=?').bind(id).run();return json({ok:true})}
 if(p==='/api/reports/summary'&&m==='GET'){const period=u.searchParams.get('period')||'month',date=u.searchParams.get('date')||new Date().toISOString().slice(0,10);let start=date,end=date;if(period==='month'){start=date.slice(0,7)+'-01';end=new Date(new Date(start+'T12:00:00').setMonth(new Date(start+'T12:00:00').getMonth()+1)-86400000).toISOString().slice(0,10)}else if(period==='week'){const d=new Date(date+'T12:00:00'),day=(d.getDay()+6)%7;start=new Date(d.getTime()-day*86400000).toISOString().slice(0,10);end=new Date(d.getTime()+(6-day)*86400000).toISOString().slice(0,10)};const [s,e,eg,mort,feed]=await Promise.all([env.DB.prepare('SELECT COALESCE(SUM(total),0)n FROM sales WHERE date BETWEEN ? AND ?').bind(start,end).first<any>(),env.DB.prepare('SELECT COALESCE(SUM(amount),0)n FROM expenses WHERE date BETWEEN ? AND ?').bind(start,end).first<any>(),env.DB.prepare('SELECT COALESCE(SUM(good_eggs+broken_eggs+dirty_eggs+small_eggs),0)n FROM egg_production WHERE date BETWEEN ? AND ?').bind(start,end).first<any>(),env.DB.prepare('SELECT COALESCE(SUM(quantity),0)n FROM mortality WHERE date BETWEEN ? AND ?').bind(start,end).first<any>(),env.DB.prepare('SELECT COALESCE(SUM(quantity_kg),0)n FROM feed_consumption WHERE date BETWEEN ? AND ?').bind(start,end).first<any>()]);return json({period,start,end,sales:num(s?.n),expenses:num(e?.n),profit:num(s?.n)-num(e?.n),eggs:num(eg?.n),mortality:num(mort?.n),feed:num(feed?.n)})}
 if(p==='/api/reports/export.csv'&&m==='GET'){const date=u.searchParams.get('date')||new Date().toISOString().slice(0,10),period=u.searchParams.get('period')||'month';let start=date,end=date;if(period==='month'){start=date.slice(0,7)+'-01';end=new Date(new Date(start+'T12:00:00').setMonth(new Date(start+'T12:00:00').getMonth()+1)-86400000).toISOString().slice(0,10)}else if(period==='week'){const d=new Date(date+'T12:00:00'),day=(d.getDay()+6)%7;start=new Date(d.getTime()-day*86400000).toISOString().slice(0,10);end=new Date(d.getTime()+(6-day)*86400000).toISOString().slice(0,10)};const sales=await env.DB.prepare('SELECT date,product_type,description,quantity,unit_price,total,payment_method,payment_status FROM sales WHERE date BETWEEN ? AND ? ORDER BY date').bind(start,end).all<any>();const ex=await env.DB.prepare('SELECT date,category,description,amount,supplier FROM expenses WHERE date BETWEEN ? AND ? ORDER BY date').bind(start,end).all<any>();const esc=(v:any)=>`"${String(v??'').replaceAll('"','""')}"`;let csv=`RELATORIO;${period};${start};${end}\n\nVENDAS\nData;Produto;Descricao;Quantidade;Preco Unitario;Total;Pagamento;Status\n`;for(const r of sales.results)csv+=[r.date,r.product_type,r.description,r.quantity,r.unit_price,r.total,r.payment_method,r.payment_status].map(esc).join(';')+'\n';csv+='\nDESPESAS\nData;Categoria;Descricao;Valor;Fornecedor\n';for(const r of ex.results)csv+=[r.date,r.category,r.description,r.amount,r.supplier].map(esc).join(';')+'\n';return new Response('\ufeff'+csv,{headers:{'content-type':'text/csv; charset=utf-8','content-disposition':`attachment; filename="granja-amazonas-${period}-${date}.csv"`}})}
 return json({error:'Rota não encontrada'},404)
 }catch(e:any){return json({error:'Erro interno',detail:e?.message||String(e)},500)}}}
